version: '3.8'

services:
  pacoder_dev:
    image: pacoder_dev
    container_name: pacoder_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules 

volumes:
  node_modules: