version: '3.8'

services:
  pacoder:
    image: pacoder
    container_name: pacoder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf